# Generated by Django 4.2.10 on 2024-08-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Make sure to submit a max of 200 characters.', max_length=200)),
                ('category', models.CharField(choices=[('OTECH Engineering Docs', 'OTECH Engineering Docs'), ('Java Training ', 'Java Training'), ('Django Training', 'Django Training'), ('Annual Plan Report', 'Annual Plan Report'), ('', 'Other')], default='OTH', max_length=200)),
                ('description', models.TextField(help_text='Make sure to submit a max of 255 characters.')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='documents/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
